//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger_scratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantNGOEnd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantNGOEnd()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int RestaurantNGOEndId { get; set; }
        public int RestaurantDashboardId { get; set; }
        public string RestaurantName { get; set; }
        public string SelectedFood { get; set; }
        public System.TimeSpan ByTime { get; set; }
        public string RestaurantLocation { get; set; }
        public string Status { get; set; }
        public Nullable<int> Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual RestaurantDashboard RestaurantDashboard { get; set; }
    }
}
