//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger_scratch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zerohungerEntities1 : DbContext
    {
        public zerohungerEntities1()
            : base("name=zerohungerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Panel> Panels { get; set; }
        public virtual DbSet<RestaurantDashboard> RestaurantDashboards { get; set; }
        public virtual DbSet<RestaurantNGOEnd> RestaurantNGOEnds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
